# Generated by Django 5.2.5 on 2025-10-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_mensagem_options_alter_mensagem_data_envio'),
        ('teacher', '0002_alter_teacher_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='serie',
            field=models.ManyToManyField(to='student.serie'),
        ),
    ]
