# Generated by Django 5.2.5 on 2025-09-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_materia_falta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falta',
            name='comentario',
            field=models.TextField(blank=True, default='-'),
        ),
    ]
