# Generated by Django 5.2.5 on 2025-09-18 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_aluno_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.materia')),
            ],
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
