# Generated by Django 5.2.5 on 2025-09-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_serie_remove_resposta_pergunta_remove_falta_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nome',
            new_name='user',
        ),
    ]
