# Generated by Django 5.2.5 on 2025-09-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_rename_valor_nota_media_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.serie'),
        ),
        migrations.AddField(
            model_name='materia',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.serie'),
            preserve_default=False,
        ),
    ]
