# Generated by Django 5.2.5 on 2025-09-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_aluno_serie_materia_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.serie'),
        ),
    ]
