# Generated by Django 5.2.5 on 2025-09-24 18:52

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_aluno_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Domingo'), (1, 'Segunda_feira'), (2, 'Terça_feira'), (3, 'Quarta_feira'), (4, 'Quinta_feira'), (5, 'Sexta_feira'), (6, 'Sabado')], default=list, max_length=13),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='forum.aluno'),
        ),
    ]
