# Generated by Django 5.2.5 on 2025-10-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_mensagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={},
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
