# Generated by Django 5.2.5 on 2025-10-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_mensagem_options_alter_mensagem_data_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='serie',
        ),
    ]
