# Generated by Django 5.2.5 on 2025-10-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_materia_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='materia',
            field=models.ManyToManyField(to='student.materia'),
        ),
    ]
