# Generated by Django 5.2.5 on 2025-10-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_serie_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='media',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
