# Generated by Django 5.2.5 on 2025-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_aluno_media_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='media',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
