# Generated by Django 5.2.5 on 2025-10-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_aluno_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='media',
            field=models.FloatField(null=True),
        ),
    ]
