# Generated by Django 5.2.5 on 2025-10-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_aluno_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='media',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='student.aluno'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='materia',
            field=models.ManyToManyField(null=True, to='student.materia'),
        ),
    ]
