# Generated by Django 5.2.5 on 2025-11-03 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_aluno_media_alter_avaliacao_aluno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataDeVencimento', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('link', models.URLField()),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('dataDePagamento', models.DateField(blank=True, null=True, verbose_name='Data De Pagamento')),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('atualizadoEm', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
