# Generated by Django 5.2.5 on 2025-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
