# Generated by Django 5.2.5 on 2025-11-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_boleto_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='link',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='materia',
            field=models.ManyToManyField(to='student.materia'),
        ),
    ]
