# Generated by Django 5.2.7 on 2025-11-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_boleto_link_alter_serie_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='link',
        ),
    ]
