name: Django CI with Selenium

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip libnss3 libxss1 libappindicator3-1 fonts-liberation
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and Chromedriver
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+')
          DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION || curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: Connect.settings
        run: |
          python manage.py test
