name: Django CI with Selenium

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip libnss3 libxss1 libappindicator3-1 fonts-liberation
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chromedriver@latest

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: Connect.settings
        run: |
          python manage.py test
