name: Django CI with Selenium

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2  

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Django server
        run: |
          python manage.py runserver &
          sleep 5
          echo "Django server started"

      - name: Run E2E Tests
        run: |
          python manage.py test
          echo "Testes concluidos"

  deploy:
    needs: test  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Iniciando Deploy"
        curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys
