name: Django CI/CD with Selenium (Firefox)

on:
  push:
    branches:
      - dev

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Install Firefox and geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          pip install geckodriver-autoinstaller
        
      - name: Setup Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run Django tests
        run: |
          export DISPLAY=:99
          python manage.py test    